name: Test Workflow

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build And Push
        uses: ./
        with:
          image: gradle-ci-test
          dockerfile: ./test/Dockerfile
          username: fengwenhao
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          addTimestamp: true
          addLatest: true
          timeZone: Asia/Shanghai
