name: Test Workflow

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'

      - name: Docker Login
        uses: ./action.yaml
        with:
          registry: fengwenhao
          image: gradle-ci-test
          dockerfile: ./test/Dockerfile
          directory: ./test
          username: fengwenhao
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          addTimestamp: true
          addLatest: true
          timeZone: Asia/Shanghai
